### ISSUE TITLE
can't resolve (Android studio)

### ISSUE THREAD

**Issue by borjaruiz** [nbsp-team/MaterialFilePicker#1]
Error:(60, 13) Failed to resolve: com.nbsp:library:1.01
<a href="openFile:/Users/Borja/Downloads/MindTheChat/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by eladbitton** [comment]
I have that problem too. Tried to use the jar and the project library. Android studio can't resolve this project

**Comment by lukaville** [comment]
Please wait a little bit, I fix it soon.

**Comment by tatocaster** [comment]
yeah , the same problem, waiting..

**Comment by ayushhgoyal** [comment]
Waiting

**Comment by lukaville** [comment]
Sorry, there are problem with maven central repository.

To resolve dependency, explicitly declare this repository:
```
repositories {
    maven {
        url  "http://dl.bintray.com/lukaville/maven" 
    }
}
```

See sample project: https://github.com/nbsp-team/MaterialFilePicker/blob/master/app/build.gradle
