### ISSUE TITLE
Opening intended directory

### ISSUE THREAD

**Issue by Ornolfr** [nbsp-team/MaterialFilePicker#10]
Hi,
How can I put some extra in the intent that would open not the starting directory, but app's directory or any else directory that I wish?

Just something like this implemented would be very appreciated:
`intent.putExtra(FilePickerActivity.ARG_PATH, /*My path*/);`

**Comment by artemnikitin** [comment]
Hi. It seems that they added this in the last commit https://github.com/nbsp-team/MaterialFilePicker/commit/4b9a19bbda0f8312ea85e60813056ed2c433bf17
