### ISSUE TITLE
wrong links provided by maven repository 

### ISSUE THREAD

**Issue by ovginkel** [nbsp-team/MaterialFilePicker#101]
When attempting to implement material file picker, gradle fails with:
ERROR: failed to resolve: com.nbsp:library:1.8
because when browsing to http://dl.bintray.com/lukaville/maven/ all the href links are incorrectly prepended by a colon:
e.g. :com/
And as you can guess the bintray repo does not automatically translate:
http://dl.bintray.com/lukaville/maven/:com/
to the correct address:
http://dl.bintray.com/lukaville/maven/com/
This goes for all subsequent folders down the line... fix bintray and you will fix a lot of problems.

**Comment by alosoft** [comment]
You are right, am not able to sync it in my project

**Comment by ovginkel** [comment]
Seems to be fixed. Thanks.
