### ISSUE TITLE
No file is shown in Android Q

### ISSUE THREAD

**Issue by alifhasnain** [nbsp-team/MaterialFilePicker#104]
No file/folder is shown in Android 10 (android studio default emulator).

**Comment by grgouala** [comment]
You should add the following code in your manifest

<application 
       **android:requestLegacyExternalStorage="true"** ........ >

**Comment by alifhasnain** [comment]
I fixed it after reading about scoped storage. Thanks 😊

**Comment by iadcialim** [comment]
@alifhasnain Can share your fix?
