### ISSUE TITLE
Get Input Stream out of Intent

### ISSUE THREAD

**Issue by Daniel63656** [nbsp-team/MaterialFilePicker#107]
The onActivityResult method provides you with an Intent. But how can I get an input Stream out of that?
And how to read the name of the chosen file?

**Comment by dimorinny** [comment]
Hello. Please see this example: https://github.com/nbsp-team/MaterialFilePicker/blob/master/app/src/main/java/com/nbsp/materialfilepicker/sample/MainActivity.kt#L97-L110

You're able to get a path of the chosen file from the intent and then using standard java APIs to open a file and get input stream from it.
