### ISSUE TITLE
doesn't support  androidx.fragment.app.Fragment

### ISSUE THREAD

**Issue by mahan-ym** [nbsp-team/MaterialFilePicker#127]
![Screenshot 2021-03-01 145554](https://user-images.githubusercontent.com/36126226/109490980-40789d80-7a9e-11eb-84c8-146e618f8823.png)

**Comment by Juby210** [comment]
There's `.withSupportFragment` method for that.

**Comment by mahan-ym** [comment]
yes you are right, thank you.
