### ISSUE TITLE
Will not work on Android M

### ISSUE THREAD

**Issue by romeoordos** [nbsp-team/MaterialFilePicker#13]
Hi!

You should use [this manual](http://developer.android.com/intl/ru/training/permissions/requesting.html) and add

`ActivityCompat.requestPermissions(this, new String[]{Manifest.permission.READ_EXTERNAL_STORAGE}, SOME_REQUEST_CONSTANT);`

 to **FilePickerActivity.onCreate()** to provide your library with access to external storage. Otherwise it will not work on Android M.

P.S. And please make minSdkVersion = 10 for your library to cover all active android versions on market. Thanks.

**Comment by bethinner** [comment]
@romeoordos thanks

**Comment by lgallard** [comment]
It applies to Android 6+

**Comment by rizwandogar111** [comment]
unable to customize FilePickerActivity.OnCreate method

**Comment by lucas22** [comment]
@rizwandogar111 alternatively you can add it to your code:

```
if(ContextCompat.checkSelfPermission(ActBuilder.this, 
android.Manifest.permission.READ_EXTERNAL_STORAGE) != PackageManager.PERMISSION_GRANTED) {
                    // permission not granted, requesting it:
                    ActivityCompat.requestPermissions(ActBuilder.this, new String[]{android.Manifest.permission.READ_EXTERNAL_STORAGE}, READ_EXTERNAL_STORAGE);
                }
                else {
                    // permission already granted, do something
                }
```

**Comment by dimorinny** [comment]
You should handle runtime permissions in activity, from what you called Material File Picker like this

I will add this information to README
