### ISSUE TITLE
Inconsistent module metadata

### ISSUE THREAD

**Issue by orfeomorello** [nbsp-team/MaterialFilePicker#2]
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
> Could not resolve com.nbsp:library:1.01.
> inconsistent module metadata found. Descriptor: com.nbsp:material-file-picker:1.01 Errors: bad module name: expected='library' found='material-file-picker'

**Comment by lukaville** [comment]
See #1
