### ISSUE TITLE
How to use it from inside Fragment?

### ISSUE THREAD

**Issue by atultiwari** [nbsp-team/MaterialFilePicker#25]
Thank you very much for this library.
I am having issue to get the selected file name from inside the Fragment, as 

> onActivityResult 

is not working (called) in fragment.
How to make this work?
Thanks.

**Comment by dimorinny** [comment]
You should use [fragment's startActivityForResult](https://developer.android.com/reference/android/app/Fragment.html#startActivityForResult(android.content.Intent, int)) and handle response in [fragment's onActivityResult](https://developer.android.com/reference/android/app/Fragment.html#onActivityResult(int, int, android.content.Intent)) method. Click [here](http://stackoverflow.com/questions/6147884/onactivityresult-not-being-called-in-fragment) for more details.

Still, problem may occur if you use nested fragment API. Click [here](http://stackoverflow.com/questions/13580075/onactivityresult-not-called-in-new-nested-fragment-api) for more information.

**Comment by atultiwari** [comment]
Thank you for getting back to me. Before posting the issue, I had gone through similar questions on StackOverflow including the one you shared.
Based on those, this is what I was able to do so far -

(I) In my MainActivity, I have `onActivityResult` call as follows -
```
    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);

        Log.d(TAG, "onActivityResult triggered from Activity");
        if (requestCode == 1 && resultCode == RESULT_OK) {
            String filePath = data.getStringExtra(FilePickerActivity.RESULT_FILE_PATH);
            Log.d(TAG, "filePath (from Activity) => " + filePath);
            SettingsFragment.textDemo.setText(filePath);
        }
    }
```

(II) In SettingsFragment, declared the TextView as public static, because eventually, I need the Result inside that TextView only.
`public static TextView textDemo;`

(III) In SettingsFragment, I tried to call `onActivityResult` as follows -
```
    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        Log.d(TAG, "onActivityResult triggered (from Fragment)");
        if (requestCode == 1 && resultCode == Activity.RESULT_OK) {
            String filePath = data.getStringExtra(FilePickerActivity.RESULT_FILE_PATH);
            Log.d(TAG, "filePath (from Fragment) => " + filePath);
            textDemo.setText(filePath);
        }
    }

```
From the logs, I found that no matter, how I modify (or shuffle) these codes, `startActivityForResult` always triggers `onActivityResult ` from the Activity only, Never from the fragment.
As evident, by this method, I can get the output I wanted, but this does not appear to be the best/ideal way to do this. I have to be extra careful that this part of code never gets called when SettingsFragment is Not opened, as then, it would result in throwing up error due to using TextView `textDemo` of SettingsFragment.

P.S. -
1. In the Stackoverflow link you provided, one suggestion was to use `this` in `onActivityResult` of the Fragment. But where can I use that?
2. Few of the answers suggested that this problem has been fixed in Android Support Library 23.2+, and I am using Android Support Library 23.4. So it should have been fixed. So is this the normal behaviour / method to call `onActivityResult ` from Fragment?

How should I do this?
Thank you.

**Comment by lukaville** [comment]
Hi. The problem may be in incorrect call of startActivityForResult. In this case you have to call `startActivityForResult` in [**Fragment**](https://developer.android.com/reference/android/app/Fragment.html#startActivityForResult(android.content.Intent, int)) class, not in Activity class: `getActivity().startActivityForResult(...)` - wrong.

Also problem might occur if you are using MaterialFilePicker builder class (with `withActivity` method). Starting activities from Fragment's using builder class haven't supported yet. You should manually create Intent and start it using Fragment's `startActivityForResult` method.

Please, show us how do you start FilePickerActivity.

**Comment by atultiwari** [comment]
OK. I was about to post the same. I was making a mistake of using MaterialFilePicker builder class from Fragment. After some trials and errors, I tried to test by making Intent and `startActivityForResult`, it worked as expected. Seems like you had already posted about it,
Thanks for this library and your help.
