### ISSUE TITLE
Filter

### ISSUE THREAD

**Issue by shahabiii** [nbsp-team/MaterialFilePicker#29]
How can set more than one filter ?
for example   just show .txt files and .mp4 files !
how ?

**Comment by lukaville** [comment]
You can use any capability of regular expressions. In this case you can use [alternation](http://www.regular-expressions.info/alternation.html):
`.*\\.(txt|mp4)$

**Comment by dimorinny** [comment]
#22

**Comment by cetintas41** [comment]
.withFilter(Pattern.compile("^.*\\.(accdb|txt|mp4)$")) // includes just .accdb .txt and .mp4

**Comment by satnamvision** [comment]
it should be .withFilter(Pattern.compile("^.*.(pdf|txt|mp3|png|jpg|jpeg)$")) 
for anyone like me who stuck on this, seeking for help and have tried already all the solutions given :) ;) :P
