### ISSUE TITLE
Couldn't get the library to load using maven dependencies.

### ISSUE THREAD

**Issue by avafab** [nbsp-team/MaterialFilePicker#3]
Error:A problem occurred configuring project ':app'.

> Could not resolve all dependencies for configuration ':app:_debugCompile'.
> Could not resolve com.nbsp:library:1.01.
>      Required by:
>          chocoprint:app:unspecified
>       > Could not resolve com.nbsp:library:1.01.
>          > inconsistent module metadata found. Descriptor: com.nbsp:material-file-picker:1.01 Errors: bad module name: expected='library' found='material-file-picker'
>       > Could not resolve com.nbsp:library:1.01.
>          > Could not get resource 'http://dl.bintray.com/lukaville/maven/com/nbsp/library/1.01/library-1.01.pom'.
>             > Could not HEAD 'http://dl.bintray.com/lukaville/maven/com/nbsp/library/1.01/library-1.01.pom'.
>                > ukproxycam.paconsulting.com

**Comment by teinvdlugt** [comment]
Same with me

**Comment by pedrofsn** [comment]
On my top-level build file (gradle):
[...]
allprojects {
    repositories {
        jcenter()
        maven {
            url "http://dl.bintray.com/lukaville/maven"
        }
    }
}

**Comment by shivam17** [comment]
After doing this, the app crashes on starting, saying Unfortunately, <AppName> has crashed.
Any way i can debug this?

**Comment by Grace5921** [comment]
yeah me too

**Comment by lukaville** [comment]
The library has been published to jcenter.

Now to add it to your project you need to add `jcenter()` repo to the repositories:
```
repositories {
    jcenter()
}
```

And then add the library itself:
```
dependencies {
    ...
    implementation 'com.nbsp:materialfilepicker:1.9'
}
```
