### ISSUE TITLE
not able to add filter 

### ISSUE THREAD

**Issue by himank1991** [nbsp-team/MaterialFilePicker#30]
if i use this MaterialFilePicker and set filter i dont get any results

new MaterialFilePicker()
                        .withActivity(QuickCvRegistration.this)
                        .withRequestCode(12346)
                        .withFilter(Pattern.compile(".*\\.txt$")) // Filtering files and directories by file name using regexp
                        .withFilterDirectories(true) // Set directories filterable (false by default)
                        .withHiddenFiles(true) // Show hidden files and folders
                        .start();

**Comment by lukaville** [comment]
Regular expression ".*\.txt$" means that you filter all files excluding files with "txt" extension. Maybe there is no *.txt files on your device.

**Comment by himank1991** [comment]
i have text file in my device and also tried with Jpeg but i am not able to get any files in filesUtils.java class their i am getting files.length = 0

**Comment by himank1991** [comment]
filtering is happening but only in one directory even when i dont give any start path or current path i.e. in root directory because of which it was not showing any files. please tell me how to include folder in search result when filter is true

**Comment by himank1991** [comment]
thanks for the help
