### ISSUE TITLE
Show only directories with specific file type

### ISSUE THREAD

**Issue by tuhin10** [nbsp-team/MaterialFilePicker#33]
Is it possible to show only directories with specific file type(say .mp3) ?

**Comment by matejperejda** [comment]
Yes, it is. You should use ".withFilter(Pattern.compile(".*\\.yourFormatHere$"))" in MaterialFilePicker builder.

```
 new MaterialFilePicker()
                .withActivity(this)
                .withRequestCode(Defaults.DIRECTORY_CHOOSER_REQUEST)
                .withFilter(Pattern.compile(".*\\.jpg$")) // Filtering files and directories by file name using regexp
                .withFilterDirectories(false) // Set directories filterable (false by default)
                .withHiddenFiles(true) // Show hidden files and folders
                .start();
```

**Comment by dimorinny** [comment]
@matejperejda I think that he meant another behaviour.

@tuhin10 We're not going to implement it, because it not common use case. You may include material file picker as library and implement it in your project.

**Comment by adibh7** [comment]
why i can't use two file in a filter
new MaterialFilePicker()
.withActivity(this)
.withFilter(Pattern.compile(".\.jpg$,.\.apk$"))
.withRequestCode(FILE_PICKER_REQUEST_CODE)
.withHiddenFiles(true)
.withTitle("Sample title")
.start();
