### ISSUE TITLE
Request code returns different

### ISSUE THREAD

**Issue by eladbitton** [nbsp-team/MaterialFilePicker#5]
I put the request code = 1 as you said. The request code that gets to the onActivityResult is 131073.

**Comment by lukaville** [comment]
Show me the code, where you call startActivityForResult.

**Comment by eladbitton** [comment]
I call it on 'onCreateView' which in     public class SectionsPagerAdapter extends FragmentPagerAdapter. The onActivityResult is on the main activity. I've managed to work this around by checking if (requestCode == 131073 && resultCode == RESULT_OK)... It is just a bit weird

**Comment by lukaville** [comment]
Check this: http://stackoverflow.com/questions/10564474/wrong-requestcode-in-onactivityresult
In fragments call startActivityForResult like this:
```getActivity().startActivityForResult(intent, 1);```

And also it would be nice to extract `1` to static constant without hardcoding magic numbers.

**Comment by eladbitton** [comment]
Thanks a lot! Works fine now
