### ISSUE TITLE
Library not working with newest Android versions

### ISSUE THREAD

**Issue by GediminasZukas** [nbsp-team/MaterialFilePicker#52]
This library is not working with Android version >= 6.

No directories are shown probably because of permission-granting related issue mentioned here #13 

I tested this libarry on device with Android 4.4 and it works and looks nice there. So would be great to have support for the newest Android versions too ;)

**Comment by GediminasZukas** [comment]
I found out (would be nice that it would be mentioned in documentation) in sample project that I have to implement permission granting functionality by myself for Android >= 6. However, it would be nice that permission handling functionality would be part of the library and would leave user hands free of writing this permission boilerplate code as it is in many other libraries.

**Comment by YuanWenHai** [comment]
Can solve this problem by just simply change the target api to the version that below API 23,but using permission granting  is much better.

**Comment by borhub** [comment]
I just copy and pasted the sample code from https://github.com/nbsp-team/MaterialFilePicker/blob/master/app/src/main/java/com/dimorinny/sample/MainActivity.java#L40-L71 , but granted it would be nice if the README referred to it.

**Comment by dimorinny** [comment]
I added information about runtime permissions to README.
