### ISSUE TITLE
Create new file / folder FAB

### ISSUE THREAD

**Issue by TheDiamondYT1** [nbsp-team/MaterialFilePicker#53]
A FAB with the option to create a file or folder would be nice. maybe use this layout ? 

![alt](https://lh3.googleusercontent.com/VNYVBPHfTgMsKB07UasBBk7AXpxgEwHwwtLRdezecNtAb7xtL2E606JIYteSo6l82Ss=h310-rw)
(That specific implementation was done using https://github.com/Clans/FloatingActionButton)

**Comment by dimorinny** [comment]
The main usecase for this library is picking file. Not creating. You can find another libraries or create MaterialFileCreator :)
