### ISSUE TITLE
Can't specify the start directory

### ISSUE THREAD

**Issue by IAmDarush** [nbsp-team/MaterialFilePicker#63]
Using the following code I am not able to get to the required directory when the file picker starts. I use the `withPath(String path)` method, because I want the user to go back and forth from that particular directory. It only changes the toolbar path text. But the file picker starts from the root directory instead of the specified directory. Can you please tell me what is wrong?

```
new MaterialFilePicker()
                .withActivity(MainActivity.this)
                .withRequestCode(500)
                .withPath(Environment.getExternalStorageDirectory().toString() + "/myFolder")
                .withFilter(Pattern.compile(".*\\.*$")) // Filtering files and directories by file name using regexp
                .withFilterDirectories(true) // Set directories filterable (false by default)
                .withHiddenFiles(true) // Show hidden files and folders
                .start();

```
The documentation states about withPath() method: 

> Specifies start directory for picker, which will be shown to user at the beginning

**Comment by GrenderG** [comment]
Are u using version `1.4`?

**Comment by DarushDev** [comment]
My bad, I was using version 1.1. Thanks for the prompt reply. It is working like a charm now.

**Comment by GrenderG** [comment]
Yeah don't worry, that issue was fixed only a [few days ago](https://github.com/nbsp-team/MaterialFilePicker/pull/62).
