### ISSUE TITLE
Changing orientation changes directory too

### ISSUE THREAD

**Issue by skytreader** [nbsp-team/MaterialFilePicker#69]
Using version 1.6 on Google Pixel. If I change the orientation of the device from portrait to landscape while picking a file, the current directory moves up (ala `cd ..`).

Invoked as

         new MaterialFilePicker().withActivity(a).withRequestCode
                (1).withFilter(Pattern.compile(".*\\.mp3")).withHiddenFiles(false).withPath
                        (lastDirectory);

Is this expected behavior?

**Comment by owniz** [comment]
I have solved that issue and submitted a PR #67 

I'm waiting for it to be accepted.

**Comment by skytreader** [comment]
Is a version with #67 going to be released soon? Project readme is still advertising 1.6.

**Comment by owniz** [comment]
Hi @lukaville are you going to release the new changes?

**Comment by lukaville** [comment]
Hi. Sorry for the delay. I've published new version recently (see project readme). It may take a few hours to complete maven central publishing.

**Comment by owniz** [comment]
Thank you!
