### ISSUE TITLE
problem with swipe to refresh

### ISSUE THREAD

**Issue by maxwellnewage** [nbsp-team/MaterialFilePicker#7]
I was updated your lib to 1.03 and SwipeRefreshLayout died. If I do a downgrade to 1.02 it works again but appears the bug with the language...

**Comment by lukaville** [comment]
Make sure that you are using latest version of support libary:
`compile 'com.android.support:support-v4:23.1.1'`

**Comment by maxwellnewage** [comment]
I have this version:

`compile 'com.android.support:appcompat-v7:23.0.1'`

**Comment by lukaville** [comment]
What does "SwipeRefreshLayout died" mean? Could you post more information such as a stacktrace or an error message?

**Comment by maxwellnewage** [comment]
I dont have errors on log or compile, nothing. But if I run my app, when I try to swipe, it does not work as if he had never implemented...

**Comment by sur2548** [comment]
Please tell me how do i change theme of MaterialFilePicker?

**Comment by maxwellnewage** [comment]
solved in last version!
