### ISSUE TITLE
FILTER NOT WORK

### ISSUE THREAD

**Issue by ahmaadyunus** [nbsp-team/MaterialFilePicker#73]
Use this library and i filter according the example with .jpg extention file. the file is exist on my storage but all file not show while file picker open . why ?

 MaterialFilePicker()
                        .withActivity(this)
                        .withFilter(Pattern.compile(".*\\.jpg$"))
                        .withRequestCode(1)
                        .withFilterDirectories(true) // Set directories filterable (false by default)
                        .withHiddenFiles(true) // Show hidden files and folders
                        .start()

**Comment by zeevy** [comment]
```
MaterialFilePicker()
.withActivity(this)
.withFilter(Pattern.compile(".*\\.jpg$"))
.withRequestCode(1)
.withFilterDirectories(true) // Set directories filterable (false by default)
.withHiddenFiles(true) // Show hidden files and folders
.start()
```

**Comment by adibh7** [comment]
why i can't use to file in a filter
new MaterialFilePicker()
                .withActivity(this)
                .withFilter(Pattern.compile(".*\\.jpg$,.*\\.apk$"))
                .withRequestCode(FILE_PICKER_REQUEST_CODE)
                .withHiddenFiles(true)
                .withTitle("Sample title")
                .start();

**Comment by Daniel63656** [comment]
.withFilter(Pattern.compile(".*\\.(jpg$|apk$)"))

This worked for me

**Comment by lukaville** [comment]
Hi,
Please make sure that you use a correct regular expression. You can check it online for example here https://regex101.com/.
Feel free to reopen the issue if you have any problems.
