### ISSUE TITLE
Latest version 1.8 or 1.09??

### ISSUE THREAD

**Issue by drmrbrewer** [nbsp-team/MaterialFilePicker#74]
Currently I'm using:

    repositories {
        maven {
            url "http://dl.bintray.com/lukaville/maven"
        }
    }
    dependencies {
        compile 'com.nbsp:library:1.8'
    }

But gradle is reporting that there is a newer version available: `1.09`.

This doesn't match with what the library code is suggesting, which is still `1.8`.  And when I accept the change to `1.09`, there is a compile error complaining that it cannot find the method `.getIntent()`.

Any idea what's going on?

**Comment by lukaville** [comment]
The latest version is `1.8`

**Comment by drmrbrewer** [comment]
@lukaville ok thank... I'm curious to know where gradle is getting the `1.09` from... do you know?  Generally then it suggests that there is a newer version available, it is indeed correct.

**Comment by drmrbrewer** [comment]
@lukaville as per the following:

![newversion](https://user-images.githubusercontent.com/9009792/32341391-471ac65c-bff5-11e7-95d2-1f859fec01e9.png)

This never used to happen.
