### ISSUE TITLE
Unable to get any result when implementing MaterialFilePicker inside Fragment

### ISSUE THREAD

**Issue by Rohit3901** [nbsp-team/MaterialFilePicker#86]
1st Approach
         new MaterialFilePicker()
                        .withActivity(getActivity())
                        .withRequestCode(10)
                        .withFilter(Pattern.compile(".*\\.pdf$")) 
                        .start();
2nd Approach
    Intent intent = new Intent(getActivity(), FilePickerActivity.class);
                ArrayList filters = new ArrayList();
                filters.add(new PatternFilter(Pattern.compile(".*\\.pdf$"), false));
                intent.putExtra(FilePickerActivity.ARG_FILTER, new CompositeFilter(filters));
                startActivityForResult(intent, 10);

In both approach unable to get any result.

**Comment by zeevy** [comment]
In your activity

```
    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);

        // if you are using "FragmentPagerAdapter" then bellow two lines
        Fragment fragment = getSupportFragmentManager().findFragmentByTag("android:switcher:" + R.id.tab_layout_pager + ":" + 1);
        if(fragment != null) fragment.onActivityResult(requestCode, resultCode, data);

    }

```

**Comment by ending0421** [comment]
@Rohit3901  new MaterialFilePicker()
              .withSupportFragment( this )  that you can get result in fragment onActivityResult callback

**Comment by dimorinny** [comment]
Don't forget to override `super.onActivityResult(requestCode, resultCode, data)` in your host Activity.
