### ISSUE TITLE
File type / file extension filter

### ISSUE THREAD

**Issue by lgallard** [nbsp-team/MaterialFilePicker#9]
I would be great to have a way to filter file types by extension, for example: *.pdf, *.jpg

Thanks in advance!

**Comment by jaymoh** [comment]
it is awesome, could you please implement a way to filter files too...

**Comment by dimorinny** [comment]
Look at [README](https://github.com/nbsp-team/MaterialFilePicker/blob/master/README.md) and update library to version 1.04.

**Comment by lgallard** [comment]
Thanks it works like a charm!

**Comment by jaymoh** [comment]
Thanks so much @dimorinny  , the library works really fine, although wouldn't you have compiled with android support library version 23.1.1? as the latest version 23.2 still has bugs causing apps to crash, that are being fixed by Google devs. You could email me directly, if updating the library again is quite a task.

**Comment by lgallard** [comment]
I got this error report from my app in Google Apps, can be this related to @jaymoh comment?

```
Caused by: android.content.res.Resources$NotFoundException: File res/drawable-v19/abc_ic_ab_back_material.xml from drawable resource ID #0x7f020016
```

**Comment by lgallard** [comment]
I had to switch to aFileChooser :(

**Comment by dimorinny** [comment]
I'll try to fix it tommorow.

<img src="https://cloud.githubusercontent.com/assets/9587692/13380103/ee337c42-de4a-11e5-84d0-f26d26251ceb.png" height="100"/>

**Comment by lgallard** [comment]
HI @dimorinny, I was trying for two days updating SDK, BuildTools, but 23.2.0 really crashes my app in Android 4.4 (maybe lower versions are affected as well,  but I got reports from Google Console for 4.4). Chrashes are due to [this](https://medium.com/@chrisbanes/appcompat-v23-2-age-of-the-vectors-91cbafa87c88#.nja9kkcvj). But even using the suggested fix other issues arise.

I use aFileChooser as my last resort, but to be hostnes it's look and feel is "old-fashion". I really like you MaterialFilePicker because it uses Material Design.

Please if you can test your library in a 4.4 it would be great, if not I can test it and give you feedback.

Regards,

**Comment by lukaville** [comment]
I've downgraded appcompat support library. Maybe it fixed this issue.

**Comment by jaymoh** [comment]
am greatful @lukaville , lemme test it right away, I was still still using 1.3

**Comment by jaymoh** [comment]
hi @lukaville Is it possible you downgrade even the RecyclerView library to 23.1.1 also, just all of them. For now I can't risk using 23.2 anytime soon, it has caused me enough stress since i tried upgrading in android studio.

**Comment by lukaville** [comment]
Ok, I've downgraded all support libraries, check out new version.

**Comment by lgallard** [comment]
@lukaville it works with library version 1.0.7 on devices with Android 4.4 and lower.
