### ISSUE TITLE
Error with back button

### ISSUE THREAD

**Issue by vincent-herreros** [nbsp-team/MaterialFilePicker#90]
Hello
I have a problem with the back button on the toolbar. It works fine except when I'm at the start of my files, in "/storage/emulated/0". I've got a FATAL ERROR. I don't find any solution to my problem.
Thanks for your times.

**Comment by vasiledoe** [comment]
Make sure you check for OK code in activity onResult like:

`        if (requestCode ==FilesHandler.YOUR_CODE&& resultCode == RESULT_OK) {
`

**Comment by vincent-herreros** [comment]
Thanks you !!
Problem solved, and I had to add "?" on the Intent data.
