### ISSUE TITLE
Install from Maven Central

### ISSUE THREAD

**Issue by Rudloff** [nbsp-team/MaterialFilePicker#91]
Hello,

I see your library is published on a custom repository and not on Maven Central anymore because you had some troubles with (https://github.com/nbsp-team/MaterialFilePicker/issues/1).

Is there any plan to publish it back on Maven Central?

(I am an [F-Droid](https://f-droid.org/) contributor and our policy is too only get libraries from trusted repositories live Maven Central or jCenter so we can't currently build apps that use your library.)

**Comment by lukaville** [comment]
Hello,

We published the library to jcenter :)

Thank you
