### ISSUE TITLE
Prohibit to move parent folder than start folder.

### ISSUE THREAD

**Issue by bidasknakayama** [nbsp-team/MaterialFilePicker#93]
Hi 

Is there any option to prohibit user from moving up than starting folder ?

[Parent folder] - [Start folder]-[sub folder] -- (files).

When I click [<-] Left arrow button, I can move to parent.
I want to stop it...

Please advice me..

**Comment by dimorinny** [comment]
Hello, sure, you can use `.withPath(String path)` to specify a path, when a user is supposed to start his journey and `.withRootPath(String path)` to specify a root (the maximum root folder). After achieving it left arrow button will lead him out of a picker Activity.
