### ISSUE TITLE
No static field action_close of type I in class Lcom/nbsp/materialfilepicker/R$id

### ISSUE THREAD

**Issue by titrouan** [nbsp-team/MaterialFilePicker#96]
Hi ! Have this error after button click to launch Material File Picker
java.lang.NoSuchFieldError: No static field action_close of type I in class Lcom/nbsp/materialfilepicker/R$id
thanks to say me what I have to do.
(sorry for my english, I'me french ;) )

**Comment by jacek23** [comment]
Same here. I start the activity from fragment, but I don't think that it's a problem

**Comment by Bryanalmo** [comment]
Hello! I have the same error, it seems that the action_close variable does not exist in the class com.nbsp.materialfilepicker.R as seen in the image

![image](https://user-images.githubusercontent.com/40524653/51125188-198f7c80-17ee-11e9-9423-90fa6a566331.png)

But it exists in the class, so I do not understand why it does not work

![image](https://user-images.githubusercontent.com/40524653/51125272-4479d080-17ee-11e9-821c-3f3e17f36d1b.png)

I will really appreciate your help! Thank you

**Comment by Dorokhovyegor** [comment]
it's happens, because you have in your project directory "menu" with file "menu.xml". Just rename it

**Comment by dimorinny** [comment]
Thank you a lot for your answer. I'm going to close that issue, feel free to open it back if the problem in our side.
