### ISSUE TITLE
Library has an issue 

### ISSUE THREAD

**Issue by akardas16** [nbsp-team/MaterialFilePicker#99]
when I launched activity the logcat says  
Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
        at com.nbsp.materialfilepicker.ui.FilePickerActivity.onCreateOptionsMenu(FilePickerActivity.java:187)

I checked library and I found you defined a wrong varable :   "private Boolean mCloseable;  "
I think it should be  "private boolean mCloseable;"

**Comment by dimorinny** [comment]
We've already fixed it. Check 1.9 version.
